### ISSUE TITLE
Can't open files with "\n\r,;" in the name.

### ISSUE THREAD

**Issue by andrewgregory** [Tux/Spreadsheet-Read#14]
Commit 63087b40a63736a1ba35233430b0368088917fd0 uses the contents of the string passed to ReadData to determine if it's a file path or content to be parsed directly.  This makes it impossible to pass file names that contain any of the characters `\n\r,;`.

**Comment by Tux** [comment]
That is intentional. I need to add docs though.
Files with newlines and carriage return are reason to panic
A semi-colon is something you'd never want in a file
Using a , is IMHO also something that should be discouraged

**Comment by andrewgregory** [comment]
All of those are legal file name characters.  Why artificially limit what file names Spreadsheet::Read can open?  As the developer, I don't have control over the names of the files my software is given.  This change means that I can't use Spreadsheet::Read directly and I'll have to use a wrapper solely for the sake of handling file names with these characters.

**Comment by Tux** [comment]
In my 30+ years of Linux/Unix/*OS I have *never* ever encountered a filename with a \r or \n in it
I have seen filenames with a ,
I Only saw filenames with a ; on VMS
I will have a second look, but the code before the patch broke more than the current state limits

**Comment by andrewgregory** [comment]
Clearly you're luckier than I am.  What exactly was broken before?  Frankly, the whole concept of allowing both file names and raw data to both be passed as simple scalars seems fundamentally broken to me.  There is no way for the caller to be sure which it will be interpreted as without checking the source for ReadData.  Even then, the use of `-f` to choose between the two means there's no way to be 100% sure.  Why not do what most modules do and use a simple scalar for a file name and a scalar ref for raw data?

**Comment by Tux** [comment]
Oké, fixed. But I am now on a network that forbids VPN and SSH, so I cannot push

**Comment by Tux** [comment]
@andrewgregory pushed. please verify. If oké, I'll release when I have a fully functional internet again

**Comment by andrewgregory** [comment]
Works for me.  One note about the commit message/change log though, this enables opening files with those characters in *any* format, not just CSV.

**Comment by Tux** [comment]
Comment changed and released. Closing
