### ISSUE TITLE
XLSX stream parsing doesnt work with Spreadsheet::ParseXLSX

### ISSUE THREAD

**Issue by 0x62ash** [Tux/Spreadsheet-Read#21]
`ReadData ($data, parser => 'xlsx')`

Spreadsheet::ParseXLSX->parse () requires file name, file handle or scalar ref, but Spreadsheet::Read::ReadData () call parser with scalar argument - https://github.com/Tux/Spreadsheet-Read/blob/master/Read.pm#L572-L576

I think that ReadData () should pass scalar ref to parse () or opened in-memory file handle via string.

**Comment by Tux** [comment]
I think it does what you think it should do already:
``` perl
use Spreadsheet::Read;

{   open my $fh, "<", "files/test.xlsx";
    my $ss = ReadData ($fh, parser => "xlsx", verbose => 3, debug => 3);
    close $fh;
    }

{   open my $fh, "<", "files/test.xlsx";
    my $data = do { local $/; <$fh> };
    close $fh;
    my $ss = ReadData (\$data, parser => "xlsx", verbose => 3, debug => 3);
    }
```
→
```
Opening XLSX GLOB(0x153c0b0) using Spreadsheet::ParseXLSX-0.27
        2 sheets
        Sheet 2 'Sheet1' 4 x 4
        Sheet 3 'Second Sheet' 3 x 5
Opening XLSX SCALAR(0x157fa30) using Spreadsheet::ParseXLSX-0.27
        2 sheets
        Sheet 2 'Sheet1' 4 x 4
        Sheet 3 'Second Sheet' 3 x 5
```
If not, can you provide me with code that shows the failure?

**Comment by 0x62ash** [comment]
My failure code is already in my first message - `ReadData ($data, parser => 'xlsx')`.

My work-around right now is to use in-memory file-handler `open (my $fh, '<', \$data)`.


You can ether fix `ReadData ()` to work with scalar data or remove from [documentation](https://metacpan.org/pod/Spreadsheet::Read) that ReadData () can work with scalar data.

**Comment by Tux** [comment]
As you could have seen in my reply, that already works in my version, so I really would like to see a *complete* *working* piece of code that shows the faulty behavior. The *only* thing *I* changed in my code is `($data, parser => "xlsx")` → `(\$data, parser => "xlsx")`. If you think that warrant a documentation addition, I'm all open to that.

**Comment by 0x62ash** [comment]
> The only thing I changed in my code is ($data, parser => "xlsx") → (\\$data, parser => "xlsx")

Your documentation does not mention code about working with a reference to data `(\$data)`
So you could either change documentation OR fix internals of Spreadsheet::Read::ReadData () to work with scalar data, not reference

**Comment by Tux** [comment]
I did both and pushed it.
