### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by milesatstetson** [Tux/Spreadsheet-Read#29]
Used to have this working on an earlier system without problems. Seems to be problems in the current version?

Not packaged, tried: `dnf -y install perl(Spreadsheet::Read)`
Which gives:
> Last metadata expiration check: 0:54:56 ago on Thu Nov 14 11:11:26 2019.
> No match for argument: perl(Spreadsheet::Read)
> Error: Unable to find a match

Trying CPAN:
`cpan Spreadsheet::Read `
or
`cpan HMBRAND/Spreadsheet-Read-0.81.tgz`

It comes up with the following errors:
> Warning: prerequisite Test::More 0.88 not found.
> Warning: prerequisite Test::NoWarnings 0 not found.

Tried to resolve the prerequisite errors, but wasn't able to track those down.

**Comment by Tux** [comment]
Never used `dnf`.
`cpan Spreadsheet::Read` should work.
`Test::More` is a CORE modules for which `0.88` is the minimum version supported. Current is version `1.302168`. The first perl release that comes with a recent enough `Test::More` is `5.10.1` (version `0.92`).
Current version for `Test::NoWarnings` is `1.04`.
```
$ cpan Test::More Test::NoWarnings
```
As preparation should work.
You did not state what version of perl you have. If it is too old, it might not meet the requirements. The minimum perl version supported is `5.8.1`.
Last, your CPAN mirror might be out of date (or not up-to-date).

All n all, I think this is a system or cpan configuration error and not something to blame on `Spreadsheet::Read`.

**Comment by milesatstetson** [comment]
Thank you.  Looks like setting up and configuring CPAN better solved the problem I was having.

On the installation that I was working with (Fedora 29):

This required installing the following fedora packages (via `dnf` ) to set up CPAN:
```
cpan
'perl(Test)'
'perl(Test::NoWarnings)'
perl-Spreadsheet-XLSX
```

Configure CPAN by doing the following ( `cpan`)
```
install CPAN
reload cpan
upgrade
```

Then installing the following cpan package: 
`cpan JSON::PP`

Then actually install by executing:
`cpan Spreadsheet::ParseExcel Spreadsheet::XLSX Spreadsheet::Read`

**Comment by Tux** [comment]
@milesatstetson do **not** use `Spreadsheet::XLSX`! Use `Spreadsheet::ParseXLSX` instead.
FWIW Max is working with my help on `Spreadsheet::ParseODS` and making fixes to `Spreadsheet::ReadSXC` along the way. The latter is already supported in `Spreadsheet::Read`, and `Spreadsheet::ParseODS` is in pre-alfa support on github.
