### ISSUE TITLE
Also accept .xlsm files as being Excel2007 files

### ISSUE THREAD

**Issue by gvrooij65** [Tux/Spreadsheet-Read#30]
xlsm is an extension used for xlsx files with macro's. With the attached patch, they are correctly recognized. Better would of course to not have this depend on the file extension but on file(1) magic only. I do not know the code well enough to fix this though.
[patch.txt](https://github.com/Tux/Spreadsheet-Read/files/4419517/patch.txt)

**Comment by Tux** [comment]
It is patched (back in April) and it will be in the upcoming 0.82
