### ISSUE TITLE
(feature request) xlscat option to join multi-line content into single line

### ISSUE THREAD

**Issue by immaxchen** [Tux/Spreadsheet-Read#32]
Thank you for developing this useful software
Here's the issue: spreadsheet cells may contain multi-line content
However, when these cells being printed using xlscat, it will produce undesired result

Example:

Name,Age,"Height
(unit: cm)","Weight
(unit: kg)"
"John Doe",20,180,70

Desired:

Name,Age,"Height (unit: cm)","Weight (unit: kg)"
"John Doe",20,180,70

I could open a PR if you like it :)

**Comment by Tux** [comment]
For any given record or for the header only?
```
$ examples/xlscat test.csv
Name │ Age │ Height
(unit: cm) │ Weight
(unit: kg)
John Doe │ 20 │ 180 │ 70
     4 x      2
$ examples/xlscat test.csv --csv
Name,Age,"Height
(unit: cm)","Weight
(unit: kg)"
"John Doe",20,180,70
     4 x      2
$ examples/xlscat test.csv --csv -N
Name,Age,"Height (unit: cm)","Weight (unit: kg)"
"John Doe",20,180,70
     4 x      2
$ examples/xlscat test.csv --csv -N ␤
Name,Age,"Height␤(unit: cm)","Weight␤(unit: kg)"
"John Doe",20,180,70
     4 x      2
```

**Comment by immaxchen** [comment]
For any given record I suppose, another useful scenario from the web:

![pros and cons](https://www.researchgate.net/profile/Ben_Hoselton/publication/304161648/figure/tbl1/AS:668876949975046@1536484100324/Pros-and-Cons-of-Similar-Products_W640.jpg)

If possible, allowing multiple characters like ". " (period and a space) or "; " (semicolon and a space) could even make more sense, thank you!

**Comment by Tux** [comment]
Multiple characters were already an option in what I implemented:
```
$ examples/xlscat --csv -N "; " test.csv
Name,Age,"Height; (unit: cm)","Weight; (unit: kg)"
"John Doe",20,180,70
     4 x      2
```
Feel free to fetch and play/experiment
```
 $ git clone https://github.com/Tux/Spreadsheet-Read Spreadsheet-Read

or get it as a tgz:

 $ wget --output-document=Spreadsheet-Read-git.tgz \
           'https://github.com/Tux/Spreadsheet-Read/archive/master.tar.gz'
```
I can do a release if you want, but I rather wait for better Spreadsheet::ParseODS support

**Comment by immaxchen** [comment]
Wow, already done?!  sure no hurry for release, thank you so much!
