### ISSUE TITLE
Doc display of 'attr' array appears to be missing a closing square bracket

### ISSUE THREAD

**Issue by tbrowder** [Tux/Spreadsheet-Read#33]
I am working on unpacking the data returned from this module's ReadData function using Raku's module Inline::Perl5. When I look at this module's main document on the CPAN website I can't see the closing square bracket on the 'attr' key's array value.

Kudos to you for an excellent and very useful module!

**Comment by Tux** [comment]
That, and a comma. Thank you for spotting. Fixed in c798193c717ff40a0601aa62dc62799dba48a22a
