### ISSUE TITLE
Minor function naming issues

### ISSUE THREAD

**Issue by dbooth-boston** [Tux/Spreadsheet-Read#36]
Thanks for making this module!  Some minor naming issues:

1. The function you call `pivot` should be called `transpose`.  That's that standard term for this matrix operation.  I suggest defining `transpose` as an alias, and maybe deprecating `pivot`.
2. The function you call `strip` has historically been called `trim` in other programming languages.  I suggest defining `trim` as an alias, and maybe deprecating `strip`.

**Comment by Tux** [comment]
Done in https://github.com/Tux/Spreadsheet-Read/commit/025ddf99b3b6340823eb5808c8bd00c772d314f3
Would that suffice?

**Comment by dbooth-boston** [comment]
Yes, thanks!
