### ISSUE TITLE
 xlsx2csv script error

### ISSUE THREAD

**Issue by sskr-18** [Tux/Spreadsheet-Read#37]
I am using xlsx2csv script to convert xlsx to csv, I am getting the following error 

Parser for XLSX is not installed at xlsx2csv line 113.

**Comment by Tux** [comment]
So, what is unclear about that message?
Install an XLSX parser that is supported by Spreadsheet::Read (the [docs](https://github.com/Tux/Spreadsheet-Read/blob/master/doc/Spreadsheet-Read.md#description) clearly state what modules are supported).
```
-- cpanm
$ sudo cpanm Spreadsheet::ParseXLSX

-- CPAN
$ sudo cpan Spreadsheet::ParseXLSX

-- Debian/Raspbian
$ sudo apt-get install -y libspreadsheet-parsexlsx-perl

-- openSUSE : this module is deprecated and should not be used
$ sudo zypper in perl-Spreadsheet-XLSX

-- CentOS/Rocky/RHEL: this module is deprecated and should not be used
$ sudo dnf install -y perl-Spreadsheet-XLSX
```
