### ISSUE TITLE
Can't install...

### ISSUE THREAD

**Issue by jjn1056** [Tux/Spreadsheet-Read#4]
Hi,  I get an error installing the latest:

dev@ix:~/src/ix$ cpanm --verbose --install Spreadsheet::Read
cpanm (App::cpanminus) 1.7038 on perl 5.020000 built for x86_64-linux
Work directory is /home/dev/.cpanm/work/1435590474.7425
You have make /usr/bin/make
You have LWP 6.08
You have /bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Spreadsheet::Read () on cpanmetadb ...
--> Working on Spreadsheet::Read
Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Spreadsheet-Read-0.61.tgz ... OK
Unpacking Spreadsheet-Read-0.61.tgz
Spreadsheet-Read-0.61/
Spreadsheet-Read-0.61/examples/
Spreadsheet-Read-0.61/examples/xls2csv
Spreadsheet-Read-0.61/examples/ss-dups-tk.pl
Spreadsheet-Read-0.61/examples/xlscat
Spreadsheet-Read-0.61/examples/ssdiff
Spreadsheet-Read-0.61/examples/ss2tk
Spreadsheet-Read-0.61/Changes
Spreadsheet-Read-0.61/META.yml
Spreadsheet-Read-0.61/MANIFEST
Spreadsheet-Read-0.61/Read.pm
Spreadsheet-Read-0.61/Makefile.PL
Spreadsheet-Read-0.61/files/
Spreadsheet-Read-0.61/files/merged.xlsx
Spreadsheet-Read-0.61/files/empty.sxc
Spreadsheet-Read-0.61/files/misc.xlsx
Spreadsheet-Read-0.61/files/Dates.xlsx
Spreadsheet-Read-0.61/files/test.xls
Spreadsheet-Read-0.61/files/test_x.txt
Spreadsheet-Read-0.61/files/perc.xls
Spreadsheet-Read-0.61/files/macosx.csv
Spreadsheet-Read-0.61/files/empty.ods
Spreadsheet-Read-0.61/files/attr.xlsx
Spreadsheet-Read-0.61/files/empty.txt
Spreadsheet-Read-0.61/files/empty.xlsx
Spreadsheet-Read-0.61/files/test_x.csv
Spreadsheet-Read-0.61/files/macosx.xls
Spreadsheet-Read-0.61/files/blank.xls
Spreadsheet-Read-0.61/files/test.sxc
Spreadsheet-Read-0.61/files/content.xml
Spreadsheet-Read-0.61/files/empty.sc
Spreadsheet-Read-0.61/files/perc.xlsx
Spreadsheet-Read-0.61/files/merged.xls
Spreadsheet-Read-0.61/files/test.xlsx
Spreadsheet-Read-0.61/files/test_t.txt
Spreadsheet-Read-0.61/files/test.sc
Spreadsheet-Read-0.61/files/test_m.txt
Spreadsheet-Read-0.61/files/empty.xls
Spreadsheet-Read-0.61/files/attr.ods
Spreadsheet-Read-0.61/files/blank.csv
Spreadsheet-Read-0.61/files/test.csv
Spreadsheet-Read-0.61/files/misc_ws.xls
Spreadsheet-Read-0.61/files/merged.ods
Spreadsheet-Read-0.61/files/empty.csv
Spreadsheet-Read-0.61/files/test.ods
Spreadsheet-Read-0.61/files/test.txt
Spreadsheet-Read-0.61/files/blank.xlsx
Spreadsheet-Read-0.61/files/values.xlsx
Spreadsheet-Read-0.61/files/test_m.csv
Spreadsheet-Read-0.61/files/misc.xls
Spreadsheet-Read-0.61/files/Dates.xls
Spreadsheet-Read-0.61/files/test_t.csv
Spreadsheet-Read-0.61/files/attr.xls
Spreadsheet-Read-0.61/files/values.xls
Spreadsheet-Read-0.61/README
Spreadsheet-Read-0.61/META.json
Spreadsheet-Read-0.61/t/
Spreadsheet-Read-0.61/t/50_sc.t
Spreadsheet-Read-0.61/t/46_clr.t
Spreadsheet-Read-0.61/t/20_csv.t
Spreadsheet-Read-0.61/t/36_xls.t
Spreadsheet-Read-0.61/t/35_perc.t
Spreadsheet-Read-0.61/t/64_dates.t
Spreadsheet-Read-0.61/t/21_csv.t
Spreadsheet-Read-0.61/t/65_perc.t
Spreadsheet-Read-0.61/t/63_misc.t
Spreadsheet-Read-0.61/t/00_pod.t
Spreadsheet-Read-0.61/t/60_xlsx.t
Spreadsheet-Read-0.61/t/01_pod.t
Spreadsheet-Read-0.61/t/34_dates.t
Spreadsheet-Read-0.61/t/37_merged.t
Spreadsheet-Read-0.61/t/11_call.t
Spreadsheet-Read-0.61/t/67_merged.t
Spreadsheet-Read-0.61/t/40_sxc.t
Spreadsheet-Read-0.61/t/32_fmt.t
Spreadsheet-Read-0.61/t/31_clr.t
Spreadsheet-Read-0.61/t/62_fmt.t
Spreadsheet-Read-0.61/t/23_csv.t
Spreadsheet-Read-0.61/t/10_basics.t
Spreadsheet-Read-0.61/t/30_xls.t
Spreadsheet-Read-0.61/t/61_clr.t
Spreadsheet-Read-0.61/t/51_sc.t
Spreadsheet-Read-0.61/t/24_csv.t
Spreadsheet-Read-0.61/t/33_misc.t
Spreadsheet-Read-0.61/t/45_ods.t
Spreadsheet-Read-0.61/t/22_csv.t
Entering Spreadsheet-Read-0.61
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04)
Running Makefile.PL
Configuring Spreadsheet-Read-0.61 ... Do you want to install 'xlscat' (Convert Spreadsheet to plain text or CSV) ?  [y] y
Do you want to install 'xlsgrep' (Grep pattern from Spreadsheet) ?  [y] y
Do you want to install 'ss2tk' (Show a Spreadsheet in Perl/Tk) ?  [y] y
Do you want to install 'ssdiff' (Show diff between two spreadsheets) ?  [y] y
Do you want to install 'xls2csv' (Wrapper around xlscat for easy XLS => CSV) ?  [y] y
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Spreadsheet::Read
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have Data::Dumper 0 ... Yes (2.151)
Checking if you have Exporter 0 ... Yes (5.70)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04)
Checking if you have Test::NoWarnings 0 ... Yes (1.04)
Checking if you have File::Temp 0.22 ... Yes (0.2304)
Checking if you have Test::More 0.88 ... Yes (1.001002)
Checking if you have IO::Scalar 0 ... Yes (2.110)
Checking if you have Carp 0 ... Yes (1.3301)
Checking if you have Test::Harness 0 ... Yes (3.30)
Building and testing Spreadsheet-Read-0.61 ... cp Read.pm blib/lib/Spreadsheet/Read.pm
cp examples/ssdiff blib/script/ssdiff
"/static/plenv/versions/5.20.0/bin/perl5.20.0" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/ssdiff
make: **\* No rule to make target `examples/xlsgrep', needed by`blib/script/xlsgrep'.  Stop.
FAIL
! Installing Spreadsheet::Read failed. See /home/dev/.cpanm/work/1435590474.7425/build.log for details. Retry with --force to force install it.
dev@ix:~/src/ix$

**Comment by jjn1056** [comment]
Seems to be happening for at least the last two revisions as well.  I get this from cpanmm or from carton.  It complains about the missing xlsgrep with I don't see in the tarball, but it does exist in your repo (Its excluded via the MANIFEST.SKIP file)

**Comment by jjn1056** [comment]
Ok so if I do:
 cpanm --verbose --interactive --install Spreadsheet::Read

and install in interactive mode and say:
Do you want to install 'xlsgrep' (Grep pattern from Spreadsheet) ?  [y] n

to not install xlsgrep BUT I accept all the remaining defaults everything works fine

So I think there's something up with the xslgrep.  I see it in your repo but not in the distribution tarball  (again its in MANIFEST.SKIP).  So maybe you want to make xslgrep default to N for people using automatized installers or you don't want xslgrep in MANIFEST.SKIP or something?

Verified this issue for at least the last few releases, and verified on three different machines.  Let me know if I can help more!

**Comment by Tux** [comment]
xlsgrep is identical to xlscat. the name controls the function

```
-f "examples/xlsgrep" or link "examples/xlscat", "examples/xlsgrep";
```

is the line in Makefile.PL that takes care of this. Maybe your system does not allow Makefile.PL to make a hardlink. After running

 $ perl Makefile.PL

check if examples/xlsgrep exists

**Comment by Tux** [comment]
@jjn1056 I installed cpanm on a Linux system that did not have cpanm and also missed the most recent Spreadsheet::Read version

$ cpanm --verbose --install Spreadsheet::Read

passed without any issue

What OS are you running on?

**Comment by ghost** [comment]
Hi 

I'm having a similar issue to the original poster in installing Spreadsheet::Read.

This is on a Strawberry Perl installation on a Windows 7 machine.

```
C:\Strawberry>cpanm --verbose --interactive --install Spreadsheet::Read
cpanm (App::cpanminus) 1.7034 on perl 5.022000 built for MSWin32-x86-multi-thread-64int
Work directory is C:\Users\bensonsa/.cpanm/work/1437375279.6884
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching Spreadsheet::Read () on cpanmetadb ...
--> Working on Spreadsheet::Read
Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Spreadsheet-Read-0.61.tgz ... OK
Unpacking Spreadsheet-Read-0.61.tgz
Entering Spreadsheet-Read-0.61
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04_01)
Running Makefile.PL
Configuring Spreadsheet-Read-0.61 ... Do you want to install 'xlscat' (Convert Spreadsheet to plain text or CSV) ?  [y]
Do you want to install 'xlsgrep' (Grep pattern from Spreadsheet) ?  [y]
Do you want to install 'ss2tk' (Show a Spreadsheet in Perl/Tk) ?  [y]
Do you want to install 'ssdiff' (Show diff between two spreadsheets) ?  [y]
Do you want to install 'xls2csv' (Wrapper around xlscat for easy XLS => CSV) ?  [y]
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Spreadsheet::Read
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
[Provides parsing of Microsoft Excel files]
Checking if you have Spreadsheet::ParseExcel  ... Yes (0.65)
Checking if you have Spreadsheet::ParseExcel::FmtDefault  ... Yes (0.65)
[Spreadsheet tools]
[Provides parsing of OpenOffice spreadsheets]
Checking if you have Spreadsheet::ReadSXC  ... No
==> Found missing dependencies: Spreadsheet::ReadSXC
Install the 1 optional module(s)? [y]
[Provides parsing of CSV streams]
Checking if you have Text::CSV_XS  ... Yes (1.18)
[Provides parsing of Microsoft Excel 2007 files]
Checking if you have Spreadsheet::ParseExcel::FmtDefault  ... Yes (0.65)
Checking if you have Spreadsheet::ParseXLSX  ... Yes (0.17)
Checking if you have Test::Harness 0 ... Yes (3.35)
Checking if you have Test::More 0.88 ... Yes (1.001014)
Checking if you have IO::Scalar 0 ... Yes (2.111)
Checking if you have File::Temp 0.22 ... Yes (0.2304)
Checking if you have Spreadsheet::ReadSXC 0.20 ... No
Checking if you have Exporter 0 ... Yes (5.72)
Checking if you have Carp 0 ... Yes (1.36)
Checking if you have Data::Dumper 0 ... Yes (2.158)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04_01)
Checking if you have Test::NoWarnings 0 ... Yes (1.04)
==> Found dependencies: Spreadsheet::ReadSXC
Searching Spreadsheet::ReadSXC (0.20) on cpanmetadb ...
--> Working on Spreadsheet::ReadSXC
Fetching http://www.cpan.org/authors/id/T/TE/TERHECHTE/Spreadsheet-ReadSXC-0.20.tar.gz ... OK
Unpacking Spreadsheet-ReadSXC-0.20.tar.gz
Entering Spreadsheet-ReadSXC-0.20
Checking configure dependencies from META.yml
Running Makefile.PL
Configuring Spreadsheet-ReadSXC-0.20 ... Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Spreadsheet::ReadSXC
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have XML::Parser 0 ... Yes (2.44)
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have Archive::Zip 0 ... Yes (1.46)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04_01)
Building and testing Spreadsheet-ReadSXC-0.20 ... The system cannot find the path specified.
dmake.exe:  Error code 129, while making 'blib\lib\Spreadsheet\.exists'
FAIL
! Installing Spreadsheet::ReadSXC failed. See C:\Users\bensonsa\.cpanm\work\1437375279.6884\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Spreadsheet::ReadSXC' is not installed
! Bailing out the installation for Spreadsheet-Read-0.61.

C:\Strawberry>
```

Spreadsheet::ReadSXC is optional and answering 'n' to this gives:

```
C:\Strawberry>cpanm --verbose --interactive --install Spreadsheet::Read
cpanm (App::cpanminus) 1.7034 on perl 5.022000 built for MSWin32-x86-multi-thread-64int
Work directory is C:\Users\bensonsa/.cpanm/work/1437375605.3564
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching Spreadsheet::Read () on cpanmetadb ...
--> Working on Spreadsheet::Read
Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Spreadsheet-Read-0.61.tgz ... OK
Unpacking Spreadsheet-Read-0.61.tgz
Entering Spreadsheet-Read-0.61
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04_01)
Running Makefile.PL
Configuring Spreadsheet-Read-0.61 ... Do you want to install 'xlscat' (Convert Spreadsheet to plain text or CSV) ?  [y]
Do you want to install 'xlsgrep' (Grep pattern from Spreadsheet) ?  [y]
Do you want to install 'ss2tk' (Show a Spreadsheet in Perl/Tk) ?  [y]
Do you want to install 'ssdiff' (Show diff between two spreadsheets) ?  [y]
Do you want to install 'xls2csv' (Wrapper around xlscat for easy XLS => CSV) ?  [y]
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Spreadsheet::Read
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
[Provides parsing of OpenOffice spreadsheets]
Checking if you have Spreadsheet::ReadSXC  ... No
==> Found missing dependencies: Spreadsheet::ReadSXC
Install the 1 optional module(s)? [y] n
[Spreadsheet tools]
[Provides parsing of Microsoft Excel 2007 files]
Checking if you have Spreadsheet::ParseXLSX  ... Yes (0.17)
Checking if you have Spreadsheet::ParseExcel::FmtDefault  ... Yes (0.65)
[Provides parsing of CSV streams]
Checking if you have Text::CSV_XS  ... Yes (1.18)
[Provides parsing of Microsoft Excel files]
Checking if you have Spreadsheet::ParseExcel  ... Yes (0.65)
Checking if you have Spreadsheet::ParseExcel::FmtDefault  ... Yes (0.65)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04_01)
Checking if you have Test::NoWarnings 0 ... Yes (1.04)
Checking if you have IO::Scalar 0 ... Yes (2.111)
Checking if you have Data::Dumper 0 ... Yes (2.158)
Checking if you have Test::Harness 0 ... Yes (3.35)
Checking if you have Carp 0 ... Yes (1.36)
Checking if you have File::Temp 0.22 ... Yes (0.2304)
Checking if you have Exporter 0 ... Yes (5.72)
Checking if you have Test::More 0.88 ... Yes (1.001014)
Building and testing Spreadsheet-Read-0.61 ... The system cannot find the path specified.
dmake.exe:  Error code 129, while making 'blib\lib\Spreadsheet\.exists'
FAIL
! Installing Spreadsheet::Read failed. See C:\Users\bensonsa\.cpanm\work\1437375605.3564\build.log for details. Retry with --force to force install it.

C:\Strawberry>
```

Any Ideas on how to fix this?

The lack of detail around the system cannot find the path specified is frustrating as I can't find where to look or what to do.

Thanks

**Comment by Tux** [comment]
could this be plenv related?

I just got me an account on a very fresh Ubuntu-15.04 that was missing all the goodies I like

``` sh
$ mkdir ~/bin
$ cd ~/bin
$ curl -L https://cpanmin.us/ -o cpanm
$ chmod +x cpanm
$ export PATH=$PATH":"~/bin
$ cpanm --verbose --install Spreadsheet::Read
```

```
cpanm (App::cpanminus) 1.7039 on perl 5.020002 built for x86_64-linux-gnu-thread-multi
Work directory is /home/tux/.cpanm/work/1438873770.2383
You have make /usr/bin/make
You have LWP 6.08
You have /bin/tar: tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
!
! Can't write to /usr/local/share/perl/5.20.2 and /usr/local/bin: Installing modules to /home/tux/perl5
:
:
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_pod.t ..... skipped: Test::Pod 1.00 required for testing POD
t/01_pod.t ..... skipped: Test::Pod::Covarage required for testing POD Coverage
t/10_basics.t .. ok
t/11_call.t .... ok
t/20_csv.t ..... skipped: No CSV parser found
t/21_csv.t ..... skipped: No CSV parser found
t/22_csv.t ..... skipped: No CSV parser found
t/23_csv.t ..... skipped: No CSV parser found
t/24_csv.t ..... skipped: No CSV parser found
t/30_xls.t ..... skipped: No M$-Excel parser found
t/31_clr.t ..... skipped: No M$-Excel parser found
t/32_fmt.t ..... skipped: No M$-Excel parser found
t/33_misc.t .... skipped: No M$-Excel parser found
t/34_dates.t ... skipped: No M$-Excel parser found
t/35_perc.t .... skipped: No M$-Excel parser found
t/36_xls.t ..... skipped: No M$-Excel parser found
t/37_merged.t .. skipped: No M$-Excel parser found
t/40_sxc.t ..... skipped: No SXC parser found
t/45_ods.t ..... skipped: No SXC parser found
t/46_clr.t ..... skipped: No OpenOffice ODS parser found
t/50_sc.t ...... # Parser: Spreadsheet::Read-0.61
t/50_sc.t ...... ok
t/51_sc.t ...... ok
t/60_xlsx.t .... skipped: No M$-Excel parser found
t/61_clr.t ..... skipped: No M$-Excel parser found
t/62_fmt.t ..... skipped: No M$-Excel parser found
t/63_misc.t .... skipped: No M$-Excel parser found
t/64_dates.t ... skipped: No M$-Excel parser found
t/65_perc.t .... skipped: No M$-Excel parser found
t/67_merged.t .. skipped: No M$-Excel parser found
All tests successful.
Files=29, Tests=256,  3 wallclock secs ( 0.18 usr  0.07 sys +  2.27 cusr  0.39 csys =  2.91 CPU)
Result: PASS
Installing /home/tux/perl5/lib/perl5/Spreadsheet/Read.pm
Installing /home/tux/perl5/man/man3/Spreadsheet::Read.3pm
Installing /home/tux/perl5/bin/ss2tk
Installing /home/tux/perl5/bin/ssdiff
Installing /home/tux/perl5/bin/xls2csv
Installing /home/tux/perl5/bin/xlsgrep
Installing /home/tux/perl5/bin/xlscat
Appending installation info to /home/tux/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/perllocal.pod
OK
Successfully installed Spreadsheet-Read-0.61
Installing /home/tux/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/.meta/Spreadsheet-Read-0.61/MYMETA.json
Installing /home/tux/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/.meta/Spreadsheet-Read-0.61/install.json
4 distributions installed
$ env PERL5LIB=$HOME/perl5/lib/perl5 perl -MSpreadsheet::Read -wE'say $Spreadsheet::Read::VERSION'
0.61
```

**Comment by bentglasstube** [comment]
I think the issue I've had with it has to do with not being able to create a hard link to link xlscat and xlsgrep.  It would be nice if it could fallback to create a symbolic link instead or something.  At the moment, I am unable to install this module in an automated way because it requires manual intervention to leave out the unneeded utilities.

**Comment by Tux** [comment]
point taken
care to create a PR?

**Comment by bentglasstube** [comment]
If I have some free time this afternoon, I will dig into it.

On Thu, Aug 06, 2015 at 08:22:05AM -0700, H.Merijn Brand wrote:

> point taken
> care to create a PR?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Tux/Spreadsheet-Read/issues/4#issuecomment-128409187

## 

Alan Berndt

  Either write something worth reading or do something worth writing.
    - Benjamin Franklin

**Comment by Tux** [comment]
thank you
