### ISSUE TITLE
Spreadsheet::Read not loading

### ISSUE THREAD

**Issue by ylavoie** [Tux/Spreadsheet-Read#40]
Testing modules are not loaded/defined with `use Spreadsheet::Read qw(ReadData parses);`

Z10::Just::For::Testing version 1.23 required--this is only version 1.00 at (eval 280) line 1

**Comment by Tux** [comment]
And what is the problem? What version of perl do you use?
Does the testsuite now fail for you? Does your program FAIL or not start at all?
```
$ perl -Mblib -wE'use Spreadsheet::Read qw( ReadData parses ); say Spreadsheet::Read->VERSION;'
0.85
```
