### ISSUE TITLE
Accessing worksheet data rather than a complete workbook

### ISSUE THREAD

**Issue by gsd4me** [Tux/Spreadsheet-Read#41]
May I propose a development and implementation option to be considered, based on my experience in trying to access data from particular worksheets from LibreOffice workbooks: none of my workbooks is very large, and each typically contain 5/6 worksheets with varying amounts of data but the time taken to do a read from the file takes longer than I expect (typically 20 minutes per workbook).

Firstly, I assume that when it is required to read in and access a particular sheet's data ($sheet = $book->sheet("foo")) the *complete* workbook will have had to be previously accessed via READ to populate the $book variable, and from there the $sheet variable.
Operationally I think that it would be advantageous to be able to simply 'open' the workbook (with a small amount of administration to obtain relevant base information - sheet names, sizes etc.) and then populate the $sheet variable with its associated data as required, say $sheet = $book->getMeSheetData ("sheetname"). In this way, the complete data/memory storage for the workbook can be reduced as sheets can be accessed as and when they are required, with memory being released back by the user when sheet access is no longer wanted.
I hope that this is a suggestion that you may consider as a development implementation.
Kind regards

**Comment by Tux** [comment]
You should post this request to the parser issues page. Spreadsheet::Read is just a wrapper.
Once the parser supports options like this, I can make Spreadsheet::Read pass them through.

Next, please state what parser is in effect. Performance and features vary. For LibreOffice I currently recommend [`Spreadsheet::ParseODS`](https://metacpan.org/pod/Spreadsheet::ParseODS)

**Comment by gsd4me** [comment]
Tux - thanks for getting back to me - I didn't post it in 'issues' as there is nothing wrong with the Read module - it works, but I was  commenting on how things could be made more logical, IMO.
The parser I am using was: $lSourceWorkbook = ReadData ($lSourceFileName, parser=>"ods"), but I have now switched to your recommendation of ParseODS - it seems to be quicker (saving 5 minutes per workbook, approx.) without losing any of my code functionality so things are progressing! regards ADB

**Comment by Tux** [comment]
So I assume the previous parser was Spreadsheed::XLSX, which is unmaintained and buggy.
More logical is in the eye of the beholder. What is logical to one is not to the other, and that is why we have options in most perl modules. I do see your use case, but I keep to my my point that this is the focus area of the underlying parser to implement.
