### ISSUE TITLE
xlsx2csv reports No parser for XLSX found

### ISSUE THREAD

**Issue by jkeenan** [Tux/Spreadsheet-Read#48]
I am attempting to help out some one who complained on IRC about being unable to convert a particular file found on the web in `.xlsx` format to `.csv` format.  The file needing conversion is found [here](https://www.nist.gov/document/2018-04-16frameworkv11core1xlsx).

I downloaded the file on Linux.  (I will ultimately have to get this to work on a BSD.)  I discovered `xlsx2csv` on CPAN.  I installed necessary prereqs from CPAN and attempted to run that program, but failed.
```
$ uname -mrs
Linux 5.19.0-43-generic x86_64

$ perl -v | head -2 | tail -1
This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-linux

$ perl -MSpreadsheet::Read -E 'say q|hello world|';perl -MSpreadsheet::ReadSXC -E 'say q|hello world|'
hello world
hello world

$ which xlsx2csv
/home/jkeenan/perl5/perlbrew/perls/perl-5.36.0/bin/xlsx2csv

$ xlsx2csv -A 2018-04-16_framework_v1.1_core1.xlsx 
No parser for XLSX found
 at /home/jkeenan/perl5/perlbrew/perls/perl-5.36.0/bin/xlsx2csv line 113.
```
What am I missing?

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
1. Thou shalt **not** use Spreadsheet::ReadSXC for `xlsx` (and not for `ods` either btw)
2. Thou shalt use Spreadsheet::ParseXLSX for `xlsx`
3. Spreadsheet::ReadSXC is for `ods` and is deprecated and unmaintained. Use Spreadsheet::ParseODS for `ods` instead.
4. I advice to uninstall Spreadsheet::ReadSXC and install Spreadsheet::ParseODS and Spreadsheet::ParseXLSX

Your report only tells me that the modules can load, but not what version is available.

**Comment by jkeenan** [comment]
The problem I was presented with was that someone was having difficult translating a `.xlsx` file into a `.csv` file.  I said to `$self`, that problem has to have already been solved in Perl.  I went to Metacpan, entered `xlsx` in the search bar, and `xlsx2csv` came up immediately, which brought me to the docs for [`xlsx2csv`](https://metacpan.org/pod/xlsx2csv) and which identifies `xlsx2csv` as being distributed with the Spreadsheet-Read documentation.  On that web page there is no mention of Spreadsheet::Parse.  So I used `cpan` to install `Spreadsheet::Read`, noted that that installed `xlsx2csv`, and tried to use it on the file in question (which, for the record, can be downloaded from [here](https://www.nist.gov/document/2018-04-16frameworkv11core1xlsx).  When my first attempt failed, I continued to poke around CPAN, which is how, for better or worse, I came upon Spreadsheet::ReadSXC.

> 1. Thou shalt **not** use Spreadsheet::ReadSXC for `xlsx` (and not for `ods` either btw)
> 
>     2. Thou shalt use Spreadsheet::ParseXLSX for `xlsx`
> 

As noted above, nothing in the docs for `xlsx2csv` hinted at Spreadsheet::ParseXLSX.

>     3. Spreadsheet::ReadSXC is for `ods` and is deprecated and unmaintained. Use Spreadsheet::ParseODS for `ods` instead.
> 
>     4. I advice to uninstall Spreadsheet::ReadSXC and install Spreadsheet::ParseODS and Spreadsheet::ParseXLSX
> 
> 

In this `perl` installation I used `cpan` rather than `cpanm`, so I didn't have 'uninstall' capacity.  Nonetheless, I installed Spreadsheet::ParseODS and Spreadsheet::ParseXLSX and proceeded to get good results (see below).

> Your report only tells me that the modules can load, but not what version is available.

These were the latest versions from CPAN.

As mentioned above, I got good results on Linux with perl-5.36.0 and this command:
```
$ xlsx2csv -A 2018-04-16_framework_v1.1_core1.xlsx
```
... which created `2018-04-16_framework_v1.1_core1-Sheet1.csv`.  I manually inspected that and opened it in LibreOffice as well.

To make sure I understood what was happening I have repeated the procedure on OpenBSD (since that's the OS the complainant is likely to be using).  I built a perl from tag `perl-5.36.1`, used `cpan` to install (per your instruction) Spreadsheet::ParseODS and Spreadsheet::ParseXLSX.
```
$ ./bin/cpan Spreadsheet::ParseODS Spreadsheet::ParseXLSX
```
That, of course, did not get `xlsx2csv` installed, so I said:
```
$ ./bin/cpan Spreadsheet::ReadODS Spreadsheet::ReadXLSX                    
```
At that point I downloaded the document and invoked `xlsx2csv` as above.  That failed with a message indicating that I still had to install Text::CVS_XS.
```
$ ./bin/cpan Text::CSV_XS
```
At that point I was able to call:
```
./bin/xlsx2csv -A ~/Downloads/2018-04-16_framework_v1.1_core1.xlsx
```
... and get a usable CSV file, `~/Downloads/2018-04-16_framework_v1.1_core1-Sheet1.csv`.

**Summary**

`xslx2csv` DWIMmed for me, but I feel its installation requirements are insufficiently documented.  I had the time available to figure it out (and file this ticket), but other potential users of `xslx2csv` might not be so patient.

**Comment by Tux** [comment]
I now see your point. I can see if I can come up with a more useful message. I am open to suggestions from the field!
Thanks for the clear path to this situation

I added the scripts as something useful as I use that on a day-to-day process myself, so it DWIM's for me :)

**Comment by jkeenan** [comment]
> 
> I added the scripts as something useful as I use that on a day-to-day process myself, so it DWIM's for me :)

Yeah, that's what I figured.  If you want to keep this ticket open as a reminder to yourself to review the docs, do so.  Otherwise, I don't need it to stay open.  Thanks.

**Comment by Tux** [comment]
I have pushed some changes. Can you give me feedback to its usefullness?

**Comment by jkeenan** [comment]
I checked out Spreadsheet-Read from GH at 78af38860edfa7b86e9a78281b179c586e9b1c91, called `perl Makefile.PL && make`, responding `y` to each of the do-you-want-to-install prompts.  I then called:
```
./blib/script/xlsx2csv -A ~/Downloads/2018-04-16_framework_v1.1_core1.xlsx
```
... and examined the resulting CSV file in both Vim and Libre Office Calc.  Results satisfactory.

But since this was mostly a documentation problem, I examined this diff:
```
git diff -w 0.87..HEAD
```
I noticed that while you added additional checks and warnings to `scripts/xlscat`, you made only small changes to `scripts/xlsx2csv` -- which was the program I needed to install to solve my colleague's problem.  This makes me wonder:  If I were approaching this problem naively -- *i.e.,* only really interested in converting XLSX to CSV and blissfully unaware of the existence of `xlscat` -- would the changes since 0.87 have enabled me to avoid the confusion that led me to file this ticket originally?

**Comment by Tux** [comment]
`xlsx2csv` calls `xlscat --csv` in the end unless you use `-A` or `-Z`. I see you **are** using `-A`, so additional diagnostics might be required inside `xlsx2csv` too.

Using `xlscat` instead would not have hinted you. Now it does.
I'm still indoubt if I'll merge the additional features of `xlsx2csv` into `xlscat` and make them just one script with symlinked aliasses.
