### ISSUE TITLE
Spreadsheet-Read-0.88 Data::Dumper version reference issue

### ISSUE THREAD

**Issue by pjwelsh** [Tux/Spreadsheet-Read#51]
Spreadsheet-Read-0.88 seems to reference a non-existing Data::Dumper version of 2.88. The newest version from cpan appears to only be 2.183: https://metacpan.org/dist/Data-Dumper
This is causing an issue with cpanspec creating a dependency requirement that can not be met. cpanspec treats versions as dependencies inspite of being labeled as "recommends".
One or more of the following locations seems to create the issue:
$ grep -r 2\.188 Spreadsheet-Read-0.88
Spreadsheet-Read-0.88/cpanfile:recommends "Data::Dumper"             => "2.188";
Spreadsheet-Read-0.88/META.yml:  Data::Dumper: '2.188'
Spreadsheet-Read-0.88/META.json:            "Data::Dumper" : "2.188",

I would ask to drop the explicit version number requirement.

**Comment by Tux** [comment]
• Data::Dumper version 2.188 is part of perl-5.38.0 and thus an existing version
• There is no *minimum* version of Data::Dumper required
• The *recommended* version of Data::Dumper is 2.188 as that is the most recent version I tested with
• If your install requires recommended versions, your setup is broken (or cpanspec is).
• You could reach out to the (co) maint of Data::Dumper to release dual-life Data::Dumper to CPAN
• This is *not* a bug in Spreadsheet::Read
• I could ease your life by making `2.188` = `suggests` and `2.183` = `recommends`, but it feels like cheating
```
$ perl -MV=Data::Dumper
Data::Dumper
        /pro/lib/perl5/5.38.0/x86_64-linux-thread-multi-quadmath/Data/Dumper.pm: 2.188
```

**Comment by pjwelsh** [comment]
Ultimately you are correct, this is an issue with cpanspec not taking into account the META* "recommends:" -vs- "requires:"
At this stage I'd leave it up to you to either set reasonable recommended base versions or close.

I don't know exactly how the distro packagers rebuild, but it could help more than just me ;)

For my part I will look to see if there are better options to cpanspec for building the RPM files required (and/or just "fix" my copy of Data::Dumper).

Thank you for the quick reply.

**Comment by Tux** [comment]
You could pull and see if that works, even if not 100% "correct". If it helps, it helps.
If so, I can release 0.89

**Comment by Tux** [comment]
And **please** reach out to the Data::Dumper maint people to make a new release on CPAN. Really.

**Comment by pjwelsh** [comment]
The incorporation of Data::Dumper into perl directly seems to change the "issue" submission a little. I have submitted one at:
https://github.com/Perl/perl5/issues/21622

**Comment by pjwelsh** [comment]
• I could ease your life by making 2.188 = suggests and 2.183 = recommends, but it feels like cheating

A quick test seems to indicate that all the options of requires, recommends or suggests create a "requires" equivalent in cpanspec when creating rpm packages/spec files.

**Comment by Tux** [comment]
<cry>That is really bad</cry>
I consider that a level-1 bug in cpanspec. It should never make a recommends a require unless explicitely asked for. Let alone suggests. Even if asked for, suggests and recommends should be optional and only be required if available.
I'm affraid I cannot help then

**Comment by pjwelsh** [comment]
I'm investigating using cpantorpm instead. cpantorpm has made better choices with regards to the perl module version issue that is reported here (but also has it's own issue).
Either way, I very much appreciate your help in this and effectively consider this closed as not-a-you-problem ;)
