### ISSUE TITLE
Questions about the tests

### ISSUE THREAD

**Issue by jandrew** [Tux/Spreadsheet-Read#7]
So I'm working my way through your test suite to see if I can contribute any changes to the package for integration of  ~::Reader::LibXML and I came on two issues.
1. the test file 632_fmt.t appears to require that row 4 of the tab 'Format' in the file 'attr.xlsx' be hidden but it's not.
2. The same test file also appears to call unformatted on the cell but compares the values to a 'value' or formatted call on the same cell.

Unfortunately,  I also found a bug in ~::Reader::LibXML where the 'is_merged' method for cells is not returning correctly so I want to fix that before I provide a pull request here.  If you want to wait for that I have no concerns.

**Comment by Tux** [comment]
I do not have Excel handy myself, as I work on Linux only.
There are computers that I can use at work (or with my neighbor), but doing actual Excel is hard.
I'll check the xlsx file for hidden-ness, where I think it ought to have a new tab called Hidden.
The Format tab should not be hidden

**Comment by jandrew** [comment]
No problem.

**Comment by Tux** [comment]
I found myself a xfreerdp access to a Win7 box with a Dutch M$ Office 2007
When I right-click on B4 (the cell, not the row), cell-properties, "Bescherming" (Protection? Security?) the rightmost tab, I see that "hidden" is checked.
It still shows in the sheet, so it might well be Excel is at fault

**Comment by Tux** [comment]
I just pushed a new attr.xlsx that has row 13 hidden and column D hidden in tab Format

**Comment by jandrew** [comment]
Ok,  I'll pull and test with that moving forward.
