### ISSUE TITLE
Normalize encoding of columns

### ISSUE THREAD

**Issue by dotandimet** [Tux/Spreadsheet-Read#9]
When text is pasted from Word into an Excel cell, it may be saved using a different encoding than the rest of the document.
We generate XLS files using Spreadsheet::WriteExcel or the HTML hack to be filled by users; When they upload the result and we parse it with Spreadsheet::Read, we sometimes get a cell that has "spaces after every character". On further investigation, it turns out that the text in this cell uses UCS2 encoding.
A web search reveals that Spreadseet::ParseExcel actually informs you of this when parsing the file, so it could be fixed in the code:
http://johnbokma.com/mexit/2009/02/24/spreadsheet-parse-excel-ucs2.html

PS: Our workaround is to ask the users to save the file as XLSX and upload that, but smoothing over the edge-cases nicely is exactly what I'd expect this module to do).

**Comment by Tux** [comment]
I might have a look later (busy right now).

Is it withing your area of expertise to propose a patch?

FWIW, the purpose of this module is/was _not_ to smooth out edge cases. It would be awesome if it proves to do so, but my main purpose was (and is) to feature a generalized API to the most used Spreadsheet parsers and remove the burden of remembering the differences. This purpose is almost conflicting with the aim to smooth out the edge cases. A generalized API can only document to offer what _all_ supported spreadsheet parsers support. I already stepped way over that line, and I am willing to step even further.

**Comment by Tux** [comment]
@dotandimet can I get such a file? I think this would address your issue:

```
diff --git a/Read.pm b/Read.pm
index 89c5e8a..ef3b493 100755
--- a/Read.pm
+++ b/Read.pm
@@ -34,6 +34,7 @@ our @ISA       = qw( Exporter );
 our @EXPORT    = qw( ReadData cell2cr cr2cell );
 our @EXPORT_OK = qw( parses rows cellrow row );

+use Encode       qw( decode );
 use File::Temp   qw( );
 use Data::Dumper;

@@ -625,6 +626,9 @@ sub ReadData
                        my $oWkC = $oWkS->{Cells}[$r][$c] or next;
                        #defined (my $val = $oWkC->{Val}) or next;
                        my $val = $oWkC->{Val};
+                       if (defined $val and my $enc = $oWkC->{Code}) {
+                           $enc eq "ucs2" and $val = decode ("utf-16be", $val);
+                           }
                        my $cell = cr2cell ($c + 1, $r + 1);
                        $opt{rc} and $sheet{cell}[$c + 1][$r + 1] = $val;       # Original

```

**Comment by dotandimet** [comment]
Wow, Sorry I missed your response!
I'll try and get a test file for you with the help of our Windows users.

**Comment by Tux** [comment]
Still no feedback?

**Comment by dotandimet** [comment]
Sorry, just tried to reproduce it with Office 2013 and couldn't :(

**Comment by dotandimet** [comment]
Just to confirm the fix works - ran into another problematic Excel and upgrading Spreadsheet::Read fixed the problem.
